version: '3.8'
services:
  # docker run --name mariadb --env-file ../../.env -v database:/var/lib/mysql/ --network=hello-network --rm testmariadb
  mariadb:
    container_name: 'mariadb'
    build:
      context: ./requirements/mariadb/
      args:
        MYSQL_NAME: ${MYSQL_NAME}
        MYSQL_ROOTPASS: ${MYSQL_ROOTPASS}
        MYSQL_USERNAME_ADMIN: ${MYSQL_USERNAME_ADMIN}
        MYSQL_PASSWORD_ADMIN: ${MYSQL_PASSWORD_ADMIN}
        MYSQL_USERNAME: ${MYSQL_USERNAME}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - database:/var/lib/mysql/
      # - debuglog:/var/log/
    networks:
      - inception
    restart: always
  # docker run --name wordpress --env-file ../../.env -v websit:/var/www/wordpress/ --network=hello-network --rm -it testwordpress
  wordpress:
    container_name: 'wordpress'
    build:
      context: ./requirements/wordpress/
    env_file:
      - ./.env
    volumes:
      - wordpress:/var/www/wordpress/
    networks:
      - inception
    restart: always
    depends_on:
      - mariadb
  #docker run --name nginx --env-file ../../.env -v websit:/var/www/wordpress/ --network=hello-network --cap-add=NET_ADMIN -p 9000:9000 -p 8080:80 --rm -it testnginx
  nginx:
    container_name: "nginx"
    build:
      context: ./requirements/nginx
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/wordpress/
    networks:
      - inception
    ports:
      - "80:80"
      - "443:443"
    restart: always
    depends_on:
      - wordpress
      - mariadb
  # adminer:
  #   image: adiminer
  #   restart: always
  #   ports:
  #     - 8080:8080

volumes:
  database:
    name: database
    driver: local
    driver_opts:
      type: none
      o: "bind"
      # device: $HOME/data/database
      device: /Users/shivarakii/Documents/42_coding/inception/srcs/data/database/
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: "bind"
      # device: $HOME/data/wordpress
      device: /Users/shivarakii/Documents/42_coding/inception/srcs/data/wordpress/
  # debuglog:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     device: /Users/shivarakii/Documents/42_coding/inception/logs
  #     o: bind

networks:
  inception:
    name: inception
    driver: bridge