version: '3.8'
services:
  mariadb:
    container_name: 'mariadb'
    build:
      context: ./requirements/mariadb/
      args:
        MYSQL_NAME: ${MYSQL_NAME}
        MYSQL_ROOTPASS: ${MYSQL_ROOTPASS}
        MYSQL_USERNAME_ADMIN: ${MYSQL_USERNAME_ADMIN}
        MYSQL_PASSWORD_ADMIN: ${MYSQL_PASSWORD_ADMIN}
        MYSQL_USERNAME: ${MYSQL_USERNAME}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - database:/var/lib/mysql/
    networks:
      - inception
    restart: always
  wordpress:
    container_name: 'wordpress'
    build:
      context: ./requirements/wordpress/
      args:
        MYSQL_NAME: ${MYSQL_NAME}
        MYSQL_USERNAME_ADMIN: ${MYSQL_USERNAME_ADMIN}
        MYSQL_PASSWORD_ADMIN: ${MYSQL_PASSWORD_ADMIN}
        MYSQL_HOST: ${MYSQL_HOST}
        WEB_TITLE: ${WEB_TITLE}
        WEB_EMAIL: ${WEB_EMAIL}
        DOMAIN_NAME: ${DOMAIN_NAME}
    environment:
      MYSQL_NAME: ${MYSQL_NAME}
      MYSQL_USERNAME_ADMIN: ${MYSQL_USERNAME_ADMIN}
      MYSQL_PASSWORD_ADMIN: ${MYSQL_PASSWORD_ADMIN}
      MYSQL_HOST: ${MYSQL_HOST}
      WEB_TITLE: ${WEB_TITLE}
      WEB_EMAIL: ${WEB_EMAIL}
      DOMAIN_NAME: ${DOMAIN_NAME}
    volumes:
      - wordpress:/var/www/wordpress/
    networks:
      - inception
    restart: always
    depends_on:
      - mariadb
  nginx:
    container_name: 'nginx'
    build:
      context: ./requirements/nginx
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/wordpress/
    networks:
      - inception
    ports:
      - "80:80"
      - "443:443"
    restart: always
    depends_on:
      - wordpress
      - mariadb
  # adminer:
  #   image: adiminer
  #   restart: always
  #   ports:
  #     - 8080:8080

volumes:
  database:
    name: database
    driver: local
    driver_opts:
      type: none
      o: "bind"
      # device: $HOME/data/database
      device: /Users/shivarakii/Documents/42_coding/inception/srcs/data/database/
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: "bind"
      # device: $HOME/data/wordpress
      device: /Users/shivarakii/Documents/42_coding/inception/srcs/data/wordpress/
  # debuglog:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     device: /Users/shivarakii/Documents/42_coding/inception/logs
  #     o: bind

networks:
  inception:
    name: inception
    driver: bridge